import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

// node:module 的 builtinModules 只含不带前缀的名字(如 'fs'),
// 而部分依赖(如 js-mdict)require 的是带前缀的 'node:fs',
// 两种形式都必须 external,否则浏览器平台构建无法解析。
const nodeBuiltinExternals = [...new Set(builtinModules.flatMap(m =>
    m.startsWith('node:') ? [m, m.slice('node:'.length)] : [m, `node:${m}`]
))];

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 社区免费版构建模式:
//   --release  单次发布构建(Obsidian 社区市场要求:非压缩、可读源码;剥离 console 调试日志)
//   (默认)     dev watch 模式(inline sourcemap,便于本地开发)
const mode = process.argv[2] === '--release' ? 'release' : 'dev';

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main-unified-full.ts'], // 统一多语言主入口
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...nodeBuiltinExternals],
    format: 'cjs',
    target: 'es2018',
    // 社区市场要求产物非压缩可读(政策:混淆/压缩视同闭源,case-by-case)。
    minify: false,
    logLevel: "info",
    sourcemap: mode === 'release' ? false : 'inline',
    treeShaking: true,
    // 发布构建剥离调试日志(console.log/debug/info),保留 warn/error;
    // 剥离日志不算混淆,产物仍可读。dev 构建保留日志便于排查。
    ...(mode === 'release' ? { pure: ['console.log', 'console.debug', 'console.info'] } : {}),
    outfile: 'main.js',
    loader: {
        '.html': 'text',
        '.md': 'text',
        '.svg': 'dataurl',
        '.jpg': 'dataurl',
        '.jpeg': 'dataurl',
        '.png': 'dataurl',
    },
    define: {
    },
});

if (mode === 'release') {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
